Repository Kanderson58/zingerz, pull requests merged in 2023-04, with the labels that each got.

#41 Refac/joke class refac
  src/components/App/App.tsx
  src/components/HomePage/HomePage.tsx
  src/components/Joke/Joke.tsx
  src/components/SearchPage/SearchPage.tsx
Labels: refactor

#40 Refac/typescript interfaces
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/Header/Header.tsx
  src/components/HomePage/HomePage.tsx
  src/components/Joke/Joke.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchPage/SearchPage.tsx
  src/interfaces.tsx
Labels: refactor

#44 Feat/total search
  cypress/e2e/search-page-spec.cy.ts
  src/apiCalls.tsx
  src/components/App/App.tsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchPage/SearchPage.tsx
  src/components/Sparkles/Sparkles.css
  src/components/Sparkles/Sparkles.tsx
  tsconfig.json
Labels: enhancement

#48 Feat/all search results
  src/apiCalls.tsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.tsx
Labels: enhancement

#53 Doc: add readMe information
  README.md
Labels: documentation
